// Generated by IcedCoffeeScript 1.3.3b
var easeInOut;

easeInOut = function(x) {
  return Math.pow((Math.sin((x - 0.5) * Math.PI) + 1) * 0.5, 2);
};

$(document).ready(function() {
  var canvas, gridl, gridl_s, hline, hline_s, hlines, i, lstyle, mine, mine_p, mine_s, tool, viewport, vline, vline_s, vlines, wdp, yours, yours_p, yours_s, _ref;
  window.scrollTo(0, 1);
  $(document).bind("touchmove", function(e) {
    return e.preventDefault();
  });
  wdp = (_ref = window.devicePixelRatio) != null ? _ref : 1;
  viewport = document.querySelector("meta[name=viewport]");
  viewport.setAttribute('content', "user-scalable=no, width=" + (320 * wdp) + ", height=" + (416 * wdp) + ", initial-scale=" + (1.0 / wdp) + ", maximum-scale=" + (1.0 / wdp));
  canvas = document.getElementById("canvas");
  canvas.setAttribute('width', "" + (320 * wdp));
  canvas.setAttribute('height', "" + (416 * wdp));
  paper.install(window);
  paper.setup(document.getElementById("canvas"));
  lstyle = {
    strokeColor: "white",
    strokeWidth: 2 * wdp,
    strokeCap: "round"
  };
  vline = new Path();
  vline.style = lstyle;
  vline.add([0, 0]);
  vline.add([0, 300 * wdp]);
  vline_s = new Symbol(vline);
  vlines = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 0; _i <= 10; i = ++_i) {
      _results.push(vline_s.place([i * 30 * wdp, 150 * wdp]));
    }
    return _results;
  })();
  hline = new Path();
  hline.style = lstyle;
  hline.add([0, 0]);
  hline.add([300 * wdp, 0]);
  hline_s = new Symbol(hline);
  hlines = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 0; _i <= 10; i = ++_i) {
      _results.push(hline_s.place([150 * wdp, i * 30 * wdp]));
    }
    return _results;
  })();
  gridl = new Group(vlines);
  gridl.addChildren(hlines);
  gridl_s = new Symbol(gridl);
  mine = gridl_s.place([160 * wdp, 160 * wdp]);
  mine_s = new Symbol(mine);
  mine_p = mine_s.place([160 * wdp, 160 * wdp]);
  yours = gridl_s.place([160 * wdp, 260 * wdp]);
  yours_s = new Symbol(yours);
  yours_p = yours_s.place([160 * wdp, 260 * wdp]);
  yours_p.scale(0.3, [160 * wdp, 410 * wdp]);
  view.draw();
  tool = new Tool();
  return tool.onMouseDown = function(e) {
    return view.onFrame = function(e) {
      if (e.time > 0.2) {
        view.onFrame = null;
        mine_p.remove();
        mine_p = mine_s.place([160 * wdp, 160 * wdp]);
        mine_p.scale(0.3, [160 * wdp, 10 * wdp]);
        yours_p.remove();
        yours_p = yours_s.place([160 * wdp, 260 * wdp]);
        return yours_p.scale(1, [160 * wdp, 410 * wdp]);
      } else {
        mine_p.remove();
        mine_p = yours_s.place([160 * wdp, 160 * wdp]);
        mine_p.scale(1.0 - 0.7 * easeInOut(e.time / 0.2), [160 * wdp, 10 * wdp]);
        yours_p.remove();
        yours_p = yours_s.place([160 * wdp, 260 * wdp]);
        return yours_p.scale(1.0 - 0.7 * easeInOut(1 - e.time / 0.2), [160 * wdp, 410 * wdp]);
      }
    };
  };
});